# Generated by Django 2.2.5 on 2020-09-08 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='catepory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='sku',
            old_name='is_lauched',
            new_name='is_launched',
        ),
        migrations.RenameField(
            model_name='spuspecification',
            old_name='value',
            new_name='name',
        ),
    ]
