# Generated by Django 2.2.5 on 2020-09-09 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200908_0245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SKUSpecificatin',
            new_name='SKUSpecification',
        ),
    ]
