# Generated by Django 2.2.5 on 2020-09-10 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20200909_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spu',
            old_name='sales',
            new_name='scales',
        ),
    ]
