# Generated by Django 2.2.5 on 2020-09-10 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20200910_1037'),
    ]

    operations = [
    ]
