# Generated by Django 2.2.5 on 2020-09-10 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20200910_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spu',
            old_name='scales',
            new_name='scale',
        ),
    ]
