# Generated by Django 2.2.5 on 2020-09-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20200910_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spu',
            old_name='brands',
            new_name='brand',
        ),
    ]
