# Generated by Django 2.2.5 on 2020-09-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20200910_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spu',
            old_name='scale',
            new_name='scales',
        ),
    ]
