# Generated by Django 2.2.5 on 2020-09-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20200910_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spuspecification',
            old_name='spec',
            new_name='spu',
        ),
    ]
