# Generated by Django 2.2.5 on 2020-09-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_ative'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_ative',
            new_name='email_active',
        ),
    ]
