# Generated by Django 2.2.5 on 2020-09-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200907_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='is_delete',
            new_name='is_deleted',
        ),
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='电子邮箱'),
        ),
    ]
